security:
  basic:
    enabled: true
  user:
    name: user
    password: password123
server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/it-much/config-repo-51cto-video
          username: 
          password: 
          
