security:
  basic:
    enabled: true
  user:
    name: user
    password: password123
server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/youyang87111/simple
          username: youyang87111
          password: youyang127793
          
