document.writeln(" 	<link href=\"/css/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />");
document.writeln("    <!-- Font Awesome Icons -->");
document.writeln("    <link href=\"/dist/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\" />");
document.writeln("    <!-- Ionicons -->");
document.writeln("    <link href=\"/dist/ionicons/css/ionicons.min.css\" rel=\"stylesheet\" type=\"text/css\" />");
document.writeln("    <link href=\"/js/plugin/select2/select2.min.css\" rel=\"stylesheet\" type=\"text/css\" />");
document.writeln("    <!-- Theme style -->");
document.writeln("    <link href=\"/dist/css/AdminLTE.min.css\" rel=\"stylesheet\" type=\"text/css\" />");
document.writeln("    ");
document.writeln("    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter");
document.writeln("          page. However, you can choose any other skin. Make sure you");
document.writeln("          apply the skin class to the body tag so the changes take effect.");
document.writeln("    -->");
document.writeln("    <link href=\"/dist/css/skins/_all-skins.min.css\" rel=\"stylesheet\" type=\"text/css\">");
document.writeln("    <link href=\"/dist/css/skins/skin-blue.min.css\" rel=\"stylesheet\" type=\"text/css\" />");
document.writeln("");
document.writeln("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->");
document.writeln("    <!-- WARNING: Respond.js doesn\'t work if you view the page via file:// -->");
document.writeln("    <!--[if lt IE 9]>");
document.writeln("        <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>");
document.writeln("        <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>");
document.writeln("    <![endif]-->");
document.writeln("    <!-- DATA TABLES -->");
document.writeln("    <link href=\"/js/plugin/datatables/dataTables.bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" />");
document.writeln("    <!-- iCheck -->");
document.writeln("    <link href=\"/js/plugin/iCheck/flat/blue.css\" rel=\"stylesheet\" type=\"text/css\" />");
document.writeln("    <!--messenger-->");
document.writeln("    <link href=\"/js/plugin/messenger/css/messenger.css\" rel=\"stylesheet\" type=\"text/css\"/>");
document.writeln("    <link href=\"/js/plugin/messenger/css/messenger-theme-flat.css\" rel=\"stylesheet\" type=\"text/css\"/>");
document.writeln("	<!-- daterange picker -->");
document.writeln("    <link href=\"/js/plugin/daterangepicker/daterangepicker-bs3.css\" rel=\"stylesheet\" type=\"text/css\" />");
document.writeln("    <link href=\"/js/plugin/datepicker/datepicker3.css\" rel=\"stylesheet\" type=\"text/css\" />");
document.writeln("    <link href=\"/css/common.css\" rel=\"stylesheet\" type=\"text/css\" />");
document.writeln("    <link href=\"/css/checkout.css\" rel=\"stylesheet\" type=\"text/css\" />");
document.writeln("	<!-- self_defined css -->");
document.writeln("    <link href=\"/css/new_style.css\" rel=\"stylesheet\" type=\"text/css\" />");