package com.pax.busi.resourcemgr.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ServicePortType", targetNamespace = "http://tempuri.org/KMP.xsd/Service.wsdl")
public interface ServicePortType {

	/**
	 * Service definition of function KMP__UpdateTMK
	 * 
	 * @param req
	 * @return returns com.pax.busi.webservice.STUPDATETMKRES
	 */
	@WebMethod(operationName = "UpdateTMK")
	@WebResult(name = "res", targetNamespace = "")
	@RequestWrapper(localName = "UpdateTMK", targetNamespace = "http://tempuri.org/KMP.xsd", className = "com.pax.busi.webservice.UpdateTMK")
	@ResponseWrapper(localName = "UpdateTMKResponse", targetNamespace = "http://tempuri.org/KMP.xsd", className = "com.pax.busi.webservice.UpdateTMKResponse")
	public STUPDATETMKRES updateTMK(
			@WebParam(name = "req", targetNamespace = "") STUPDATETMKREQ req);

	/**
	 * Service definition of function KMP__TmkCvt
	 * 
	 * @param cmd
	 * @param szResInfo
	 * @param iResCode
	 */
	@WebMethod(operationName = "TmkCvt")
	@RequestWrapper(localName = "TmkCvt", targetNamespace = "http://tempuri.org/KMP.xsd", className = "com.pax.busi.webservice.TmkCvt")
	@ResponseWrapper(localName = "STCVTRES", targetNamespace = "http://tempuri.org/KMP.xsd", className = "com.pax.busi.webservice.STCVTRES")
	public void tmkCvt(
			@WebParam(name = "cmd", targetNamespace = "") int cmd,
			@WebParam(name = "iResCode", targetNamespace = "", mode = WebParam.Mode.OUT) Holder<Integer> iResCode,
			@WebParam(name = "szResInfo", targetNamespace = "", mode = WebParam.Mode.OUT) Holder<String> szResInfo);

}
